# Generated by Django 3.2.5 on 2021-08-23 17:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Primers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_name', models.CharField(max_length=30)),
                ('primer_seq', models.CharField(max_length=30)),
                ('purchase_order', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('date_received', models.DateField()),
                ('date_opened', models.DateField(blank=True, null=True)),
                ('stored_freezer', models.CharField(choices=[('Freezer -20', (('1', 'Shelf 1'), ('2', 'Shelf 2'), ('3', 'Shelf 3'), ('4', 'Shelf 4'))), ('Freezer -80', (('1', 'Shelf 1'), ('2', 'Shelf 2'), ('3', 'Shelf 3'), ('4', 'Shelf 4')))], max_length=21)),
                ('stored_box', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('purchase_order', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('date_received', models.DateField()),
                ('date_opened', models.DateField(blank=True, null=True)),
                ('stored_freezer', models.CharField(choices=[('Freezer -20', (('1', 'Shelf 1'), ('2', 'Shelf 2'), ('3', 'Shelf 3'), ('4', 'Shelf 4'))), ('Freezer -80', (('1', 'Shelf 1'), ('2', 'Shelf 2'), ('3', 'Shelf 3'), ('4', 'Shelf 4')))], max_length=21)),
            ],
        ),
        migrations.CreateModel(
            name='Tissue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tissue_info', models.CharField(max_length=200)),
                ('date_received', models.DateField()),
                ('stored_freezer', models.CharField(choices=[('Freezer -20', (('1', 'Shelf 1'), ('2', 'Shelf 2'), ('3', 'Shelf 3'), ('4', 'Shelf 4'))), ('Freezer -80', (('1', 'Shelf 1'), ('2', 'Shelf 2'), ('3', 'Shelf 3'), ('4', 'Shelf 4')))], max_length=21)),
                ('stored_box', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='DNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_date', models.DateField()),
                ('stored_freezer', models.CharField(choices=[('Freezer -20', (('1', 'Shelf 1'), ('2', 'Shelf 2'), ('3', 'Shelf 3'), ('4', 'Shelf 4'))), ('Freezer -80', (('1', 'Shelf 1'), ('2', 'Shelf 2'), ('3', 'Shelf 3'), ('4', 'Shelf 4')))], max_length=21)),
                ('stored_box', models.CharField(max_length=9)),
                ('tissue_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab_inventory.tissue')),
            ],
        ),
    ]
