# Generated by Django 3.2.5 on 2021-09-16 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tissue_info', models.CharField(choices=[('Solanum lycopersicum', (('Sl - fruit', 'Solanum lycopersicum / fruit'), ('Sl - leaf', 'Solanum lycopersicum / leaf'))), ('Helianthus annuus', (('Ha - seed', 'Helianthus annuus / seed'), ('Ha - leaf', 'Helianthus annuus / leaf'))), ('Zea mays', (('Zm - seed', 'Zea mays / seed'), ('Zm - leaf', 'Zea mays / leaf'))), ('Solanum tuberosum / tuber', (('St - tuber', 'Solanum tuberosum / tuber'), ('St - leaf', 'Solanum tuberosum / leaf'))), ('Oryza sativa', (('Os - seed', 'Oryza sativa / seed'), ('Os - leaf', 'Oryza sativa / leaf'))), ('Triticum aestivum', (('Ta - seed', 'Triticum aestivum / seed'), ('Ta - leaf', 'Triticum aestivum / leaf')))], max_length=100)),
                ('extraction_date', models.DateField()),
                ('date_discarded', models.DateField(blank=True, null=True)),
                ('stored_freezer', models.CharField(choices=[('Freezer -20', (('-20/1', 'Shelf 1'), ('-20/2', 'Shelf 2'), ('-20/3', 'Shelf 3'), ('-20/4', 'Shelf 4'))), ('Freezer -80', (('-80/1', 'Shelf 1'), ('-80/2', 'Shelf 2'), ('-80/3', 'Shelf 3'), ('-80/4', 'Shelf 4')))], max_length=21)),
                ('stored_box', models.CharField(max_length=9)),
            ],
            options={
                'verbose_name_plural': 'DNA',
            },
        ),
        migrations.CreateModel(
            name='Primer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_name', models.CharField(max_length=30)),
                ('primer_seq', models.CharField(max_length=30)),
                ('purchase_order', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('date_received', models.DateField()),
                ('date_opened', models.DateField(blank=True, null=True)),
                ('date_discarded', models.DateField(blank=True, null=True)),
                ('stored_freezer', models.CharField(choices=[('Freezer -20', (('-20/1', 'Shelf 1'), ('-20/2', 'Shelf 2'), ('-20/3', 'Shelf 3'), ('-20/4', 'Shelf 4'))), ('Freezer -80', (('-80/1', 'Shelf 1'), ('-80/2', 'Shelf 2'), ('-80/3', 'Shelf 3'), ('-80/4', 'Shelf 4')))], max_length=21)),
                ('stored_box', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('purchase_order', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0)])),
                ('date_received', models.DateField()),
                ('date_opened', models.DateField(blank=True, null=True)),
                ('date_discarded', models.DateField(blank=True, null=True)),
                ('stored_freezer', models.CharField(choices=[('Freezer -20', (('-20/1', 'Shelf 1'), ('-20/2', 'Shelf 2'), ('-20/3', 'Shelf 3'), ('-20/4', 'Shelf 4'))), ('Freezer -80', (('-80/1', 'Shelf 1'), ('-80/2', 'Shelf 2'), ('-80/3', 'Shelf 3'), ('-80/4', 'Shelf 4')))], max_length=21)),
            ],
            options={
                'verbose_name_plural': 'supplies',
            },
        ),
        migrations.CreateModel(
            name='Tissue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tissue_info', models.CharField(max_length=200)),
                ('date_received', models.DateField()),
                ('date_discarded', models.DateField(blank=True, null=True)),
                ('stored_freezer', models.CharField(choices=[('Freezer -20', (('-20/1', 'Shelf 1'), ('-20/2', 'Shelf 2'), ('-20/3', 'Shelf 3'), ('-20/4', 'Shelf 4'))), ('Freezer -80', (('-80/1', 'Shelf 1'), ('-80/2', 'Shelf 2'), ('-80/3', 'Shelf 3'), ('-80/4', 'Shelf 4')))], max_length=21)),
                ('stored_box', models.CharField(max_length=9)),
            ],
        ),
    ]
