# Generated by Django 3.2.5 on 2021-08-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_inventory', '0003_alter_tissue_stored_freezer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dna',
            name='stored_freezer',
            field=models.CharField(choices=[('Freezer -20', (('-20/1', 'Shelf 1'), ('-20/2', 'Shelf 2'), ('-20/3', 'Shelf 3'), ('-20/4', 'Shelf 4'))), ('Freezer -80', (('-80/1', 'Shelf 1'), ('-80/2', 'Shelf 2'), ('-80/3', 'Shelf 3'), ('-80/4', 'Shelf 4')))], max_length=21),
        ),
        migrations.AlterField(
            model_name='primer',
            name='stored_freezer',
            field=models.CharField(choices=[('Freezer -20', (('-20/1', 'Shelf 1'), ('-20/2', 'Shelf 2'), ('-20/3', 'Shelf 3'), ('-20/4', 'Shelf 4'))), ('Freezer -80', (('-80/1', 'Shelf 1'), ('-80/2', 'Shelf 2'), ('-80/3', 'Shelf 3'), ('-80/4', 'Shelf 4')))], max_length=21),
        ),
        migrations.AlterField(
            model_name='supply',
            name='stored_freezer',
            field=models.CharField(choices=[('Freezer -20', (('-20/1', 'Shelf 1'), ('-20/2', 'Shelf 2'), ('-20/3', 'Shelf 3'), ('-20/4', 'Shelf 4'))), ('Freezer -80', (('-80/1', 'Shelf 1'), ('-80/2', 'Shelf 2'), ('-80/3', 'Shelf 3'), ('-80/4', 'Shelf 4')))], max_length=21),
        ),
    ]
